config/routes.rb
Rails.application.routes.draw do
  root to: "blog#index"

  resources :posts
end

app/models/blog.rb
class Blog
  attr_reader :entries
  attr_writer :post_source

  def initialize
    @entries = []
  end

  def new_post(*args)
    post_source.call(*args).tap do |p|
      p.blog = self
    end
  end

  def title
    "Watching Paint Dry"
  end

  def subtitle
    "The trusted source for drying paint news and opinion"
  end

  def add_entry(entry)
    entries << entry
  end

  private

  def post_source
    @post_source ||= Post.public_method(:new)
  end
end

app/models/post.rb
class Post

	attr_accessor :blog, :title, :body

  def initialize(attrs={})
    attrs.each do |k, v| send("#{k}=",v) end
  end

	def publish
		blog.add_entry(self)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :init_blog

  private

  def init_blog
    @blog = Blog.new
  end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  	@blog = Blog.new
  	post1 = @blog.new_post
  	post1.title = "Paint just applied"
  	post1.body = "Paint just applied. It's a lovely orangey-purple"
  	post.publish
  	post2 = @blog.new_post(title: "Still wet")
  	post2.body = "Paint is still quite wet. No bubbling yet!"
  	post2.publish
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = @blog.new_post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/_entry.html.erb
<article>
  <header>
    <h3><%= entry.title %></h3>
  </header>
  <p><%= entry.body %></p>
</article>

app/views/blog/index.html.erb
<h1><%= @blog.title %></h1>
<h2><%= @blog.subtitle %></h2>
<%= render partial: "entry", collection: @blog.entries %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="sidebar two columns">
  <nav>
    <ul>
      <li><%= link_to "New post...", new_post_path %></li>
    </ul>
  </nav>
</div>

<%= yield %>

</body>
</html>